### ISSUE TITLE
Parameter --texture-size doesn't work.

### ISSUE THREAD

**Issue by rafaskb** [maltaisn/msdf-gdx-gen#1]
I believe this is due to the code trying to parse it as a list of Ints, but the library used to handle parameters says only lists of Strings are supported due to Java limitations:

https://jcommander.org/#_fixed_arities

> Also, note that only List<String> is allowed for parameters that define an arity. You will have to convert these values yourself if the parameters you need are of type Integer or other (this limitation is due to Java’s erasure).

**Comment by maltaisn** [comment]
Good catch! I'll fix it in a few hours.

**Comment by maltaisn** [comment]
I fixed it and added a few other things. List of ints worked fine for some reason, maybe type was inferred from default value? Instead it looks like it was related to cbeust/jcommander#137, which was supposed to be fixed a long time ago...
