### ISSUE TITLE
Out of memory when converting a large charset (CJK)

### ISSUE THREAD

**Issue by phu54321** [maltaisn/msdf-gdx-gen#3]
I'm trying to convert a very large charset **(17144 characters)** with this tool. Note that I've gave 8GB already to JVM, but it still lacks memory and fails on 40% of progress.

> java -Xmx8g -jar msdfgen.jar -g ./msdfgen -o output -s 16 -r 4 -c cp949.txt NotoSansCJKkr-Bold.otf

- About -g option: I'm using macOS for I'm using a cmake-built msdfgen. (directly built from [github repo](https://github.com/Chlumsky/msdfgen/)).

Can this memory problem be fixed? Thanks.

[cp949.txt](https://github.com/maltaisn/msdf-gdx-gen/files/6084656/cp949.txt)
[NotoSansCJKkr-Bold.otf.zip](https://github.com/maltaisn/msdf-gdx-gen/files/6084658/NotoSansCJKkr-Bold.otf.zip)

**Comment by maltaisn** [comment]
I hadn't tested charsets that large, it's entirely possible that you run into issues. I'll look into it.

**Comment by phu54321** [comment]
For the reference, this is an example of such large charset font packed with  Hiero (SDF, apparently). 32px size with distance field of 32x scale and 4px spread.

There are 22 sheet of texture atlases, totalling to 32.7MB (88MB uncompressed). In theory this workload itself shouldn't require much memory.

vvv click to see. It's white.

![NanumBarunGothic1](https://user-images.githubusercontent.com/775265/109985897-91132380-7d48-11eb-9516-21a97aade603.png)
